### ISSUE TITLE
Pass the Exception instance to the constructor

### ISSUE THREAD

**Issue by NigelGreenway** [bouiboui/tissue#3]
Instead of having to write

``` php
Tissue::create(
        $e->getMessage(),
        $e->getCode(),
        $e->getSeverity(),
        $e->getFile(),
        $e->getLine(),
        $e->getTraceAsString()
    );
```

for each exception, would it not be better to simply pass the exception as a parameter? This would save needless code and you can simply write

``` php
try {
    // Some code
} catch (ErrorException $exception) {
    Tissue::create($exception);
}
```

You constructor will can then typehint against the root exception class

``` php
public function __construct(\Exception $exception)
{
    // your normal code
}
```

Code will be easily maintainable by both the package maintainers and package users.

**Comment by bouiboui** [comment]
I'm working on it! It will be available in the next release, tomorrow.
Thanks for the suggestion!

**Comment by NigelGreenway** [comment]
:+1:

**Comment by paragonie-scott** [comment]
:+1:

**Comment by bouiboui** [comment]
It's done, _kinda_, in the [v0.0.3](https://github.com/bouiboui/tissue/tree/v0.0.3).
_Kinda_, because I couldn't bring myself to make Tissue non-static, so you'll have to call `Tissue::createFromException($e)` instead, but I think most people will just set `Tissue::bindUncaughtExceptionHandler()` at the beginning of their code since it's even easier to implement.

**Comment by NigelGreenway** [comment]
Awesome, sorry I couldn't do a PR, but great that you changed it.

Thanks
